name: cactus
description: "Framework for running AI models on mobile devices"
version: 0.1.2
homepage: https://cactuscompute.com
repository: https://github.com/cactus-compute/cactus

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  http: ^1.2.1 
  path_provider: ^2.0.0 
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true